### PR TITLE
replaced JSON.parse with secure-json-parse across files

### PR DESCRIPTION
**Pull request by lucadonnoh**
#309 using the default configuration (throw a SyntaxError)

### CODE REVIEW

**Review by mcollina — COMMENTED** [review]
There was no need to change the tests, could you restore them?

**Comment by lucadonnoh** [comment]
yes

**Comment by lucadonnoh** [comment]
hmm...

**Comment by mcollina** [comment]
you can try adding a few `console.log(err)` in the try-catch blocks, maybe there is an error being caught there.

**Comment by jkirkpatrick24** [comment]
Looks like an error is being thrown by `secure-json-parse` when attempting to parse a buffer [here](https://github.com/mercurius-js/mercurius/pull/311/files#diff-2050061250e7c969e3895288b8da74b5340874e78239e4a82806cf6f1ecc195eR170)

The error being thrown is `TypeError: text.charCodeAt is not a function` 

I've opened up a [PR in secure-json-parse](https://github.com/fastify/secure-json-parse/pull/13) that should hopefully fix this issue 😄

**Comment by mcollina** [comment]
A better approach is to call `.toString()` before trying to parse with a `Buffer`.

**Comment by jkirkpatrick24** [comment]
@lucadonnoh secure-json-parse has been updated. I think you should be able to update to the latest version and re-open this.

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
