### PR TITLE
fix: add __resolveReference support

### PR DESCRIPTION
**Pull request by codeflyer**
This PR fixes is required to support properly the gateway.

### CODE REVIEW

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by mcollina** [comment]
Should I just ship this very quick?

**Comment by codeflyer** [comment]
> Should I just ship this very quick?

Yes, thanks. An I'll update the gateway as well

**Comment by mcollina** [comment]
What needs to be changed in the gateway?

**Comment by codeflyer** [comment]
> What needs to be changed in the gateway?

Update the package version, and fix a test.

**Pull request merged**
