### PR TITLE
doc(opentelemetry): add tracing documentation with zipkin and opentelemetry

### PR DESCRIPTION
**Pull request by PacoDu**
Waiting for `@opentelemetry/instrumentation-graphql` release.

### CODE REVIEW

**Comment by PabloSzx** [comment]
Maybe it's better for `open-telemetry.md` to be in `docs/integrations/`

**Comment by PacoDu** [comment]
Closes #179

**Comment by PacoDu** [comment]
TODO: switch to @autotelic/fastify-opentelemetry

**Comment by mcollina** [comment]
@adamovittorio PTAL

**Comment by adamovittorio** [comment]
@projectjudge FYI, we can try it with the gcp/prometheus exporter and see if we can remove the custom code for the headers propagation in fastify. Then in the ctx we have access to the tracer that we can use to instantiate custom spans.

**Comment by projectjudge** [comment]
@adamovittorio for sure, we can give it a go and update the decorator for our custom spans as well if needed

**Comment by PacoDu** [comment]
I switched to `@autotelic/fastify-opentelemetry` for the documentation. 

It's not perfect, here is the trace I get with the configuration described in the documentation:

For the `_service { sdl }` requested by the `gateway` from `service-add` I've a clean trace: 
image

But for the example query `{ add(x: 1, y: 2)`:
image

**Comment by PacoDu** [comment]
Ok ... the gateway doesn't work as expected with a query returning a Scalar, it returns null. Modifying the schema to return an object fixed the issue.

Opentelemetry is perfectly working 🎉 :
image

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by mcollina** [comment]
I think we should document that this would not work with graphql-jit. Or does it?

**Comment by PacoDu** [comment]
> I think we should document that this would not work with graphql-jit. Or does it?

I didn't test this with jit enabled, I suppose it will not work for the graphql trace, but we will still get the http trace at least. 
Maybe we can add some mercurius specific spans / attributes in another PR.

**Comment by PacoDu** [comment]
Normal:
image

Jitted:
image

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
