### PR TITLE
Swap `standard` for `neostandard`

### PR DESCRIPTION
**Pull request by voxpelli**
Follows `fastify` etc, see eg. https://github.com/fastify/fastify/pull/5509

(Disclaimer: I created `neostandard` together with Matteo and others and I was/is a co-maintainer of `standard`)

### CODE REVIEW

**Comment by mcollina** [comment]
CI fails :(

**Comment by mcollina** [comment]
you can bump minimum node to v20

**Comment by voxpelli** [comment]
@mcollina Done 👍

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
