### PR TITLE
feat: opentelemetry integration

### PR DESCRIPTION
**Pull request by PacoDu**
Mercurius works with existing tools like `@autotelic/fastify-opentelemetry` and `@opentelemetry/instrumentation-graphql`. But it's missing some mercurius specific spans and attributes that we can add with the opentelemetry API.

As a reference, here is an example of a mercurius trace with a gateway and a service and without any additional opentelemetry integration:
image

And here is an example with a simple mercurius - graphql span added to the main fastifyGraphql function and a cached attribute (see PR changes):
image
 

We need to define what we want to expose in opentelemetry traces (spans and attributes). And maybe add a `telemetry` option to mercurius so user can enable/disable telemetry ?

### CODE REVIEW

**Comment by PacoDu** [comment]
Depends on #341

**Comment by mcollina** [comment]
@PabloDu any updates on this one?

**Comment by PacoDu** [comment]
This is a demonstration of a span usage inside the mercurius library, I don't have time right now to push it further unfortunately.
If you want I can cleanup this PR and just add the tracer and the base mercurius span.

**Comment by PacoDu** [comment]
superseded by #363

**Pull request closed without merging**
