### PR TITLE
typescript docs

### PR DESCRIPTION
**Pull request by PabloSzx**
~~WIP~~

I made [https://github.com/mercurius-js/mercurius-typescript](https://github.com/mercurius-js/mercurius-typescript) for the code, to take inspiration, and testing the code while we are at it, ~~I think eventually that repo could be transferred to the org eventually too~~.

## Any suggestion is welcome

~~I am planning to at least add basic usage and [graphql-codegen](https://graphql-code-generator.com/) usage.~~

~~Maybe I can also add [nexus](https://nexusjs.org/) and [TypeGraphQL](https://typegraphql.com/) 🤔~~

---

Preview: https://pabloszx.github.io/mercurius/#/docs/typescript

### CODE REVIEW

**Comment by PabloSzx** [comment]
Just created [mercurius-codegen](https://github.com/PabloSzx/mercurius-typescript/tree/master/packages/mercurius-codegen) to further improve the TypeScript experience and simplify the usage of [GraphQL Code Generator](https://graphql-code-generator.com/) for Mercurius 🎉 

And of course it will be mentioned in these docs 👍 .

**Comment by mcollina** [comment]
Would you move this to the org? So we can make it official? It's amazing!

**Comment by PabloSzx** [comment]
> Would you move this to the org? So we can make it official? It's amazing!

Done 👍 

But now I can't update the repo description and website after it was moved 😟

**Comment by mcollina** [comment]
I've made you admin!

**Comment by mcollina** [comment]
Any updates on this?

**Comment by PabloSzx** [comment]
> Any updates on this?

Yes, I'm sorry, between working in other stuff and making mercurius-codegen I haven't worked on this specific point, I think this weekend will have progress if it's not already done

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
