### PR TITLE
Add TypeGraphQL integration docs

### PR DESCRIPTION
**Pull request by MichalLytek**
I've added integration docs for TypeGraphQL, similar to the nexus one 😉

### CODE REVIEW

**Review by PabloSzx — APPROVED** [review]

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by mcollina** [comment]
Good work!

**Comment by valdestron** [comment]
What about federation mode example? buildSchema does not generate correct schema for the gateway, can we have official example for gateway also ?

**Comment by MichalLytek** [comment]
@valdestron 
You need to do the same trick that is described in TypeGraphQL examples:
https://github.com/MichalLytek/type-graphql/blob/v1.1.1/examples/apollo-federation/helpers/buildFederatedSchema.ts

```ts
import { buildFederatedSchema, printSchema } from "@apollo/federation";
import federationDirectives from "@apollo/federation/dist/directives";
import { GraphQLResolverMap } from "apollo-graphql";
import { buildSchema, createResolversMap } from "type-graphql";
import { specifiedDirectives } from "graphql";

const baseSchema = await buildSchema({
  directives: [...specifiedDirectives, ...federationDirectives],
  resolvers,
});

const schema = buildFederatedSchema({
  typeDefs: gql(printSchema(baseSchema)),
  resolvers: createResolversMap(baseSchema) as GraphQLResolverMap<any>,
});
```

**Pull request merged**
