### PR TITLE
feat(docs): add nestjs integration docs

### PR DESCRIPTION
**Pull request by smolinari**
Hi,

I hope this is ok. I thought it would be good to add NestJS in the integrations. 

Scott

### CODE REVIEW

**Review by mcollina — COMMENTED** [review]
Wow, good work! Is this a new tutorial or it was copied from the Nest doc?

Could you please add a note on how to get help about Nest at the top? We usually do not have the bandwidth to support them.

**Review by mcollina — COMMENTED** [review]
Great work! Could you add a note at the top on where Nest.js users could get help? Usually they have specific questions and they are unable to create minimum viable reproduction just using basic module. From past experience, we'll have an hard time in supporting them.

**Comment by smolinari** [comment]
@mcollina - I put this piece together myself. But, I used some of the example code from Nest's examples, but reworked it for Fastify and Mercurius. 

I've added notes to get support both at the start and the end of the article. Also, if anyone has a question or runs into any issues following the article, I'll keep an eye out and will be glad to help them. :smiley: 

Scott

**Comment by mcollina** [comment]
It's a great piece!!

Could you add this somewhere?

```
Please refer to the Nest [Discord](discord.gg/NestJS) channel (support) for all questions regarding Nest.
```

**Comment by smolinari** [comment]
@mcollina - That is sort of what I put as the last sentence. Should I reword that?

Scott

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by mcollina** [comment]
Great work!

**Comment by jonnydgreen** [comment]
This is really nice!

**Pull request merged**
