### PR TITLE
add ErrorWithProps handler for mercurius hook

### PR DESCRIPTION
**Pull request by sooxt98**
Somehow related to this https://github.com/mercurius-js/mercurius/issues/699

### CODE REVIEW

**Comment by jonnydgreen** [comment]
Can you add some unit tests please?

**Comment by sooxt98** [comment]
@jonnydgreen done

**Comment by jonnydgreen** [comment]
Thanks, could you take a look at the rest of the tests as they are now failing?

**Comment by sooxt98** [comment]
@jonnydgreen im not quite sure what does the error means, seems like format issue, but i just copied from others test

**Comment by jonnydgreen** [comment]
Yeah it's formatting: `npx standard --fix` should do the trick!

**Comment by sooxt98** [comment]
@jonnydgreen Try again

**Review by jonnydgreen — APPROVED** [review]
LGTM

**Pull request merged**
