### PR TITLE
feat: export SubscriptionClient class

### PR DESCRIPTION
**Pull request by codeflyer**
in this PR:

- Export the SubscriptionClient
- update the type definitions
- add test to the types exported

### CODE REVIEW

**Comment by mcollina** [comment]
I would rather export it in a separate module instead. Wdyt?

**Comment by codeflyer** [comment]
> I would rather export it in a separate module instead. Wdyt?

You mean export just the Subscription Client? Or all the subscription feature?

In the first case we can build a module like `@mercurius/subscription-tools` and use them directly in the `mercurius` part that manage the subscription.

I wont extract instead the feature completely.

Wdyt?

**Comment by mcollina** [comment]
I would extract only the SubscriptionClient.

**Comment by marco-ippolito** [comment]
> I would extract only the SubscriptionClient.

this is being done here https://github.com/mercurius-js/mercurius-subscription-client/pull/3

**Comment by marco-ippolito** [comment]
@mcollina @codeflyer we can close this has has been resolved by https://github.com/mercurius-js/mercurius/pull/938

**Pull request closed without merging**
