### PR TITLE
fix test race condition, union types, & toc name

### PR DESCRIPTION
**Pull request by PabloSzx**
- Fix typescript types for unions are not following the real names in the code: https://github.com/mercurius-js/mercurius/blob/master/index.js#L294 https://github.com/mercurius-js/mercurius/blob/master/index.js#L319
- The TypeScript section is not in the main README TOC
- Subscriptions docs have a mistake in the TOC

### CODE REVIEW

**Review by mcollina — CHANGES_REQUESTED** [review]
Could you add/update a test for the type?

**Comment by PabloSzx** [comment]
> Could you add/update a test for the type?

In practice it doesn't do much, since the code is not being run, and the issue was that it was not aligned, but if you really want to, sure

**Comment by PabloSzx** [comment]
It turns out making tests for these types was a good thing, I found an interesting problem, the IFieldResolver type is conflicting with the __resolveType__ & __isTypeOf__, as the screenshots below show

 image

image

Honestly, I don't know how to fix it without making the types again / changing them considerably.

**Comment by mcollina** [comment]
Me neither, maybe @fox1t can.

**Comment by PabloSzx** [comment]
since the current fields can't be fixed without possible breaking changes, it's better to simply remove the misleading union types, since they were not working on the first place, and using [mercurius-codegen](https://github.com/mercurius-js/mercurius-typescript/tree/master/packages/mercurius-codegen) they are automatically fixed anyways.

I also fixed a race condition that was happening in the gateway/pollingInterval test

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
