### PR TITLE
docs in own files, added plugins & integrations

### PR DESCRIPTION
**Pull request by PabloSzx**
- Added Table of Contents (meanwhile the website docs is pending, and because I think the README is getting too big and hard to navigate)
- Plugins section as talked in #126 

~~Preview in https://github.com/PabloSzx/mercurius/tree/readme-patch#table-of-contents & https://github.com/PabloSzx/mercurius/tree/readme-patch#plugins~~

Preview in https://github.com/PabloSzx/mercurius/tree/readme-patch#mercurius

### CODE REVIEW

**Comment by mcollina** [comment]
@AlexNiallMalin you might need to do something about this in: https://github.com/mercurius-js/mercurius/pull/305

**Comment by mcollina** [comment]
I think it's best if we split the readme into multiple md files inside the docs folder instead. It's too big it's unmanageable.

**Comment by AlexNiallMalin** [comment]
@mcollina Yes I agree this would be the best way to go! I can sort this in the process of expanding on https://github.com/mercurius-js/mercurius/pull/305

**Review by mcollina — APPROVED** [review]
lgtm from me

are you planning any more work on this PR?

**Comment by PabloSzx** [comment]
I don't know what is your opinion on mentioning test utilities around mercurius.

I made [mercurius-integration-testing](https://github.com/PabloSzx/mercurius-integration-testing) to ease integration testing.

**Comment by PabloSzx** [comment]
Oh, in the previous commit I forgot to add `Integrations` in the main README, I just added it

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by mcollina** [comment]
Would you like to move it to the org? Then we can mention it as official.

**Pull request merged**
