### PR TITLE
Use new fastify plugin names for `@fastify/static` & `@fastify/error` & `@fastify/websocket` (#791)

### PR DESCRIPTION
**Pull request by jessekrubin**
`fastify-static & fastify-error & fastify-websocket -> @fastify/static & @fastify/error & @fastify/websocket`

### CODE REVIEW

**Review by stefanosala — APPROVED** [review]

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by arthurfiorette** [comment]
@mcollina, can this be released as 8.12.3?

**Comment by mmahkamov** [comment]
@mcollina We moved from Express to Fastify recently, with an existing TypeGraphQL codebase. The latter doesn't support GraphQL 16.x yet, so we had to switch to Mercurius 8.x. Unfortunately, now Fastify is failing to start due to #791 and this is a blocker for us.
I'd really appreciate if the fix could be released soon.

**Comment by mcollina** [comment]
Done, sorry about this!

**Comment by jessekrubin** [comment]
@mcollina thanks dude!

**Pull request merged**
